---
- name: Deploy Flask app
  hosts: all
  become: true
  remote_user: root
  gather_facts: true

  vars:
  #   yaml_file: "{{ external_yaml_file | default('project.py') }}"
    local_path: "${env.WORKSPACE}"

  tasks:
    # - name: Print out
    #   command: /bin/bash -c "cat ${env.WORKSPACE}"
    - name: Debug - List contents of the directory
      command: ls -l "{{ local_path }}"
    - name: Copy Flask app files
      copy:
        src: "test.py"
        dest: "~/flask_dir/"
        remote_src: yes

    - name: Activate virtual environment
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate"

    - name: Start Flask app
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate && export FLASK_APP=~/flask_dir/test.py && ~/flask_dir/.myenv/bin/flask run --host=0.0.0.0 --port=5000"
      async: 0
      poll: 0
