---
- name: Deploy Flask app
  hosts: all
  become: true
  remote_user: root
  gather_facts: true

  vars:
    yaml_file: "{{ external_yaml_file | default('project.py') }}"

  tasks:
    - name: Copy Flask app files
      copy:
        src: "{{ yaml_file }}"
        dest: ~/flask_dir/{{ yaml_file }}
        remote_src: yes

    - name: Activate virtual environment
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate"

    - name: Start Flask app
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate && export FLASK_APP=~/flask_dir/{{ yaml_file }} && ~/flask_dir/.myenv/bin/flask run --host=0.0.0.0 --port=5000"
      async: 0
      poll: 0
...


#Added vars to make this file performance dynamic....Find syntax below
# ansible-playbook -e "yaml_file=<name of your python file>" deploy.yml -i hosts.ini
