---
- name: Deploy Flask app
  hosts: all
  become: true
  remote_user: root
  gather_facts: true
  tasks:
    - name: Activate virtual environment
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate"

    - name: Start Flask app
      command: /bin/bash -c "export FLASK_APP=~/flask_dir/project.py && ~/flask_dir/.myenv/bin/flask run --host=0.0.0.0 --port=5000 &"
      async: 0
      poll: 0

    # - name: Get the PID of the Flask app
    #   shell: "ps aux | grep 'python3 project.py' | grep -v grep | awk '{print $2}'"
    #   register: flask_pid
    #   ignore_errors: yes

    # - name: Stop Flask app after 60 seconds
    #   shell: "sleep 60 && kill -TERM {{ flask_pid.stdout }}"
    #   ignore_errors: yes

